/** Official Data Protection Officers Conference public website copy. */

export const membershipCategories = {
  student: {
    name: "Student Membership",
    for: "For students and individuals preparing for careers in privacy, data protection, compliance, cybersecurity and data governance.",
    eligibility: [
      "University and polytechnic students",
      "Recent graduates",
      "Certification candidates",
      "Interns",
      "Entry-level privacy professionals",
    ],
    benefits: [
      "Access to selected webinars",
      "Student professional community",
      "Career guidance",
      "Internship opportunities",
      "Selected resources",
      "Conference discounts",
      "Mentorship opportunities",
      "Professional development updates",
    ],
  },
  associate: {
    name: "Associate Membership",
    for: "For early-career professionals developing practical competence in privacy, compliance and data governance.",
    eligibility: [
      "Junior compliance officers",
      "Privacy analysts",
      "Legal officers",
      "Internal auditors",
      "Risk officers",
      "Cybersecurity personnel",
      "Professionals transitioning into privacy roles",
    ],
    benefits: [
      "Quarterly professional training",
      "CPD credits",
      "Resource library access",
      "Mentorship",
      "Sector community membership",
      "Career centre access",
      "Regulatory intelligence",
      "Conference discounts",
    ],
  },
  professional: {
    name: "Professional Membership",
    for: "For certified and practising Data Protection Officers and experienced privacy professionals.",
    eligibility: ["Applicants should possess relevant professional experience, qualifications or recognised data protection certification."],
    benefits: [
      "Full access to quarterly professional training",
      "Full CPD participation",
      "Professional membership card",
      "Member verification profile",
      "Professional resource library",
      "Threat intelligence updates",
      "Sector working groups",
      "Mentorship participation",
      "Career centre access",
      "Research and publication opportunities",
      "Voting rights where applicable",
      "Discounted conference registration",
    ],
  },
  fellow: {
    name: "Fellow Membership",
    for: "For senior professionals, leaders, researchers and practitioners who have made significant contributions to privacy and data governance.",
    eligibility: ["Senior professionals who have demonstrated leadership, experience and significant contribution to data protection, privacy governance or digital trust."],
    benefits: [
      "Professional recognition",
      "Leadership opportunities",
      "Advisory and committee participation",
      "Speaking and presentation opportunities",
      "Research leadership",
      "Mentorship participation",
      "Awards and recognition eligibility",
      "Executive networking",
      "Full access to professional resources",
    ],
  },
  corporate: {
    name: "Corporate Membership",
    for: "For organisations seeking structured professional development, membership access and capacity building for their employees.",
    eligibility: [
      "Government institutions",
      "Financial institutions",
      "Fintech companies",
      "Insurance companies",
      "Telecommunications companies",
      "Universities",
      "Healthcare institutions",
      "Technology companies",
      "Data Protection Compliance Organisations",
      "Professional associations",
    ],
    benefits: [
      "Multiple staff memberships",
      "Group training access",
      "Institutional dashboard",
      "Staff CPD monitoring",
      "Conference discounts",
      "Job vacancy publication",
      "Corporate visibility",
      "Access to selected institutional resources",
      "Partnership and sponsorship opportunities",
      "Custom capacity-building support",
    ],
  },
} as const;

export const officialCommunities = [
  { name: "Banking DPO Forum", focus: ["Financial data governance", "Customer privacy", "Digital banking", "AML and privacy considerations", "Vendor management", "Cybersecurity", "Regulatory compliance"] },
  { name: "Fintech DPO Forum", focus: ["Emerging financial technologies", "Digital payments", "Lending platforms", "Identity verification", "Responsible data innovation"] },
  { name: "Insurance DPO Forum", focus: ["Insurance data governance", "Claims privacy", "Vendor risk"] },
  { name: "Government DPO Forum", focus: ["Public-sector data governance", "Citizen data protection", "Digital identity", "Government databases", "Data sharing", "Public service accountability"] },
  { name: "Education DPO Forum", focus: ["Student records", "Research data", "Digital learning platforms", "Institutional databases", "Children’s privacy"] },
  { name: "Healthcare DPO Forum", focus: ["Health information governance", "Medical confidentiality", "Patient rights", "Health technology", "Sensitive personal data"] },
  { name: "Telecommunications DPO Forum", focus: ["Subscriber information", "Communications data", "Digital identity", "Cybersecurity", "Regulatory compliance"] },
  { name: "AI Governance Working Group", focus: ["Responsible artificial intelligence", "Algorithmic accountability", "Automated decision-making", "Bias and fairness", "AI risk assessments", "Data governance", "Transparency and human oversight"] },
  { name: "Privacy Research and Innovation Group", focus: ["Research", "Academia", "Practical privacy innovation"] },
];

export const quarterlyTopics = [
  "Data protection governance",
  "NDP Act compliance",
  "Regulatory implementation updates",
  "Privacy by design",
  "Data Protection Impact Assessments",
  "Artificial intelligence governance",
  "Cybersecurity governance",
  "Incident response and breach management",
  "Vendor and third-party risk management",
  "Cross-border data transfers",
  "Privacy audits",
  "Emerging technologies and privacy",
];

export const trainingTopics = [
  "NDP Act implementation",
  "Regulatory compliance",
  "Data mapping",
  "DPIAs",
  "Privacy by design",
  "Data breach response",
  "Vendor management",
  "International data transfers",
  "Cybersecurity governance",
  "Artificial intelligence governance",
  "Privacy audits",
  "Executive reporting",
  "Data ethics",
  "Emerging technologies",
];

export const cpdActivities = [
  "Training attendance",
  "Conference participation",
  "Webinars",
  "Workshops",
  "Professional publications",
  "Research",
  "Speaking engagements",
  "Mentorship",
  "Committee service",
  "Approved external training",
];

export const awardCategories = [
  "Data Protection Officer of the Year",
  "Young Privacy Professional of the Year",
  "Privacy Innovation Award",
  "Privacy Research Excellence Award",
  "Public Sector Privacy Excellence Award",
  "Financial Sector Privacy Excellence Award",
  "Privacy Leadership Award",
  "Digital Trust Award",
  "Data Governance Excellence Award",
];
