/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AwardsRouteImport } from './routes/awards'
import { Route as BenefitsRouteImport } from './routes/benefits'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CommunitiesRouteImport } from './routes/communities'
import { Route as ConferenceRouteImport } from './routes/conference'
import { Route as ConferencesRouteImport } from './routes/conferences'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookieSettingsRouteImport } from './routes/cookie-settings'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as MentorshipRouteImport } from './routes/mentorship'
import { Route as NewsRouteImport } from './routes/news'
import { Route as PartnershipsRouteImport } from './routes/partnerships'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ThreatIntelligenceRouteImport } from './routes/threat-intelligence'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as VerifyMemberRouteImport } from './routes/verify-member'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminAwardsRouteImport } from './routes/admin.awards'
import { Route as AdminChatRouteImport } from './routes/admin.chat'
import { Route as AdminCheckInRouteImport } from './routes/admin.check-in'
import { Route as AdminCmsRouteImport } from './routes/admin.cms'
import { Route as AdminCommunitiesRouteImport } from './routes/admin.communities'
import { Route as AdminContactsRouteImport } from './routes/admin.contacts'
import { Route as AdminCpdRouteImport } from './routes/admin.cpd'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminFaqRouteImport } from './routes/admin.faq'
import { Route as AdminFeesRouteImport } from './routes/admin.fees'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminLearningRouteImport } from './routes/admin.learning'
import { Route as AdminLegalRouteImport } from './routes/admin.legal'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminMentorshipRouteImport } from './routes/admin.mentorship'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminProfileRouteImport } from './routes/admin.profile'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSpeakersRouteImport } from './routes/admin.speakers'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AwardsNominateRouteImport } from './routes/awards_.nominate'
import { Route as CareersIdRouteImport } from './routes/careers_.$id'
import { Route as ConferenceInviteRouteImport } from './routes/conference_.invite'
import { Route as ConferenceLookupRouteImport } from './routes/conference_.lookup'
import { Route as ConferenceRegisterRouteImport } from './routes/conference_.register'
import { Route as ConferenceSpeakRouteImport } from './routes/conference_.speak'
import { Route as ConferenceSponsorRouteImport } from './routes/conference_.sponsor'
import { Route as ConferencesSlugRouteImport } from './routes/conferences_.$slug'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as MembersDirectoryRouteImport } from './routes/members.directory'
import { Route as MembershipApplyRouteImport } from './routes/membership_.apply'
import { Route as NewsSlugRouteImport } from './routes/news_.$slug'
import { Route as PaymentsCallbackRouteImport } from './routes/payments.callback'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalApplicationRouteImport } from './routes/portal.application'
import { Route as PortalApplyRouteImport } from './routes/portal.apply'
import { Route as PortalCardRouteImport } from './routes/portal.card'
import { Route as PortalCareersRouteImport } from './routes/portal.careers'
import { Route as PortalCertificatesRouteImport } from './routes/portal.certificates'
import { Route as PortalChatRouteImport } from './routes/portal.chat'
import { Route as PortalCommunitiesRouteImport } from './routes/portal.communities'
import { Route as PortalCorporateRouteImport } from './routes/portal.corporate'
import { Route as PortalCpdRouteImport } from './routes/portal.cpd'
import { Route as PortalEventsRouteImport } from './routes/portal.events'
import { Route as PortalLearningRouteImport } from './routes/portal.learning'
import { Route as PortalLibraryRouteImport } from './routes/portal.library'
import { Route as PortalMentorshipRouteImport } from './routes/portal.mentorship'
import { Route as PortalMessagesRouteImport } from './routes/portal.messages'
import { Route as PortalNotificationsRouteImport } from './routes/portal.notifications'
import { Route as PortalPaymentsRouteImport } from './routes/portal.payments'
import { Route as PortalPrivacyRouteImport } from './routes/portal.privacy'
import { Route as PortalProfileRouteImport } from './routes/portal.profile'
import { Route as PortalRenewRouteImport } from './routes/portal.renew'
import { Route as PortalSupportRouteImport } from './routes/portal.support'
import { Route as PortalThreatsRouteImport } from './routes/portal.threats'
import { Route as PortalTrainingRouteImport } from './routes/portal.training'
import { Route as RegisterVerifyRouteImport } from './routes/register_.verify'
import { Route as AdminApplicationsIdRouteImport } from './routes/admin.applications_.$id'
import { Route as AdminMembersIdRouteImport } from './routes/admin.members_.$id'
import { Route as ConferencesSlugRegisterRouteImport } from './routes/conferences_.$slug_.register'
import { Route as PortalConferenceRegisterRouteImport } from './routes/portal.conference.register'
import { Route as PortalEmployerJobsRouteImport } from './routes/portal.employer.jobs'
import { Route as PortalLibraryIdRouteImport } from './routes/portal.library.$id'
import { Route as PortalMessagesThreadIdRouteImport } from './routes/portal.messages.$threadId'
import { Route as PortalTrainingIndexRouteImport } from './routes/portal.training.index'
import { Route as PortalTrainingSlugRouteImport } from './routes/portal.training.$slug'
import { Route as SeminarsSlugRegisterRouteImport } from './routes/seminars.$slug.register'
import { Route as PortalLibraryResourceIdRouteImport } from './routes/portal.library.resource.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsRoute = AwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const BenefitsRoute = BenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesRoute = CommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferenceRoute = ConferenceRouteImport.update({
  id: '/conference',
  path: '/conference',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferencesRoute = ConferencesRouteImport.update({
  id: '/conferences',
  path: '/conferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookieSettingsRoute = CookieSettingsRouteImport.update({
  id: '/cookie-settings',
  path: '/cookie-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorshipRoute = MentorshipRouteImport.update({
  id: '/mentorship',
  path: '/mentorship',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipsRoute = PartnershipsRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatIntelligenceRoute = ThreatIntelligenceRouteImport.update({
  id: '/threat-intelligence',
  path: '/threat-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyMemberRoute = VerifyMemberRouteImport.update({
  id: '/verify-member',
  path: '/verify-member',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAwardsRoute = AdminAwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatRoute = AdminChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCheckInRoute = AdminCheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommunitiesRoute = AdminCommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCpdRoute = AdminCpdRouteImport.update({
  id: '/cpd',
  path: '/cpd',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqRoute = AdminFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeesRoute = AdminFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLearningRoute = AdminLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLegalRoute = AdminLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMentorshipRoute = AdminMentorshipRouteImport.update({
  id: '/mentorship',
  path: '/mentorship',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSpeakersRoute = AdminSpeakersRouteImport.update({
  id: '/speakers',
  path: '/speakers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AwardsNominateRoute = AwardsNominateRouteImport.update({
  id: '/awards_/nominate',
  path: '/awards/nominate',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersIdRoute = CareersIdRouteImport.update({
  id: '/careers_/$id',
  path: '/careers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferenceInviteRoute = ConferenceInviteRouteImport.update({
  id: '/conference_/invite',
  path: '/conference/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferenceLookupRoute = ConferenceLookupRouteImport.update({
  id: '/conference_/lookup',
  path: '/conference/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferenceRegisterRoute = ConferenceRegisterRouteImport.update({
  id: '/conference_/register',
  path: '/conference/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferenceSpeakRoute = ConferenceSpeakRouteImport.update({
  id: '/conference_/speak',
  path: '/conference/speak',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferenceSponsorRoute = ConferenceSponsorRouteImport.update({
  id: '/conference_/sponsor',
  path: '/conference/sponsor',
  getParentRoute: () => rootRouteImport,
} as any)
const ConferencesSlugRoute = ConferencesSlugRouteImport.update({
  id: '/conferences_/$slug',
  path: '/conferences/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersDirectoryRoute = MembersDirectoryRouteImport.update({
  id: '/members/directory',
  path: '/members/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipApplyRoute = MembershipApplyRouteImport.update({
  id: '/membership_/apply',
  path: '/membership/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news_/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsCallbackRoute = PaymentsCallbackRouteImport.update({
  id: '/payments/callback',
  path: '/payments/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalApplicationRoute = PortalApplicationRouteImport.update({
  id: '/application',
  path: '/application',
  getParentRoute: () => PortalRoute,
} as any)
const PortalApplyRoute = PortalApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCardRoute = PortalCardRouteImport.update({
  id: '/card',
  path: '/card',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCareersRoute = PortalCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCertificatesRoute = PortalCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => PortalRoute,
} as any)
const PortalChatRoute = PortalChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCommunitiesRoute = PortalCommunitiesRouteImport.update({
  id: '/communities',
  path: '/communities',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCorporateRoute = PortalCorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCpdRoute = PortalCpdRouteImport.update({
  id: '/cpd',
  path: '/cpd',
  getParentRoute: () => PortalRoute,
} as any)
const PortalEventsRoute = PortalEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLearningRoute = PortalLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLibraryRoute = PortalLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMentorshipRoute = PortalMentorshipRouteImport.update({
  id: '/mentorship',
  path: '/mentorship',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMessagesRoute = PortalMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PortalRoute,
} as any)
const PortalNotificationsRoute = PortalNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPaymentsRoute = PortalPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPrivacyRoute = PortalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalRenewRoute = PortalRenewRouteImport.update({
  id: '/renew',
  path: '/renew',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSupportRoute = PortalSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => PortalRoute,
} as any)
const PortalThreatsRoute = PortalThreatsRouteImport.update({
  id: '/threats',
  path: '/threats',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTrainingRoute = PortalTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => PortalRoute,
} as any)
const RegisterVerifyRoute = RegisterVerifyRouteImport.update({
  id: '/register_/verify',
  path: '/register/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApplicationsIdRoute = AdminApplicationsIdRouteImport.update({
  id: '/applications_/$id',
  path: '/applications/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersIdRoute = AdminMembersIdRouteImport.update({
  id: '/members_/$id',
  path: '/members/$id',
  getParentRoute: () => AdminRoute,
} as any)
const ConferencesSlugRegisterRoute = ConferencesSlugRegisterRouteImport.update({
  id: '/conferences_/$slug_/register',
  path: '/conferences/$slug/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalConferenceRegisterRoute =
  PortalConferenceRegisterRouteImport.update({
    id: '/conference/register',
    path: '/conference/register',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalEmployerJobsRoute = PortalEmployerJobsRouteImport.update({
  id: '/employer/jobs',
  path: '/employer/jobs',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLibraryIdRoute = PortalLibraryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PortalLibraryRoute,
} as any)
const PortalMessagesThreadIdRoute = PortalMessagesThreadIdRouteImport.update({
  id: '/$threadId',
  path: '/$threadId',
  getParentRoute: () => PortalMessagesRoute,
} as any)
const PortalTrainingIndexRoute = PortalTrainingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalTrainingRoute,
} as any)
const PortalTrainingSlugRoute = PortalTrainingSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PortalTrainingRoute,
} as any)
const SeminarsSlugRegisterRoute = SeminarsSlugRegisterRouteImport.update({
  id: '/seminars/$slug/register',
  path: '/seminars/$slug/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLibraryResourceIdRoute = PortalLibraryResourceIdRouteImport.update({
  id: '/resource/$id',
  path: '/resource/$id',
  getParentRoute: () => PortalLibraryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/awards': typeof AwardsRoute
  '/benefits': typeof BenefitsRoute
  '/careers': typeof CareersRoute
  '/communities': typeof CommunitiesRoute
  '/conference': typeof ConferenceRoute
  '/conferences': typeof ConferencesRoute
  '/contact': typeof ContactRoute
  '/cookie-settings': typeof CookieSettingsRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/mentorship': typeof MentorshipRoute
  '/news': typeof NewsRoute
  '/partnerships': typeof PartnershipsRoute
  '/portal': typeof PortalRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/support': typeof SupportRoute
  '/threat-intelligence': typeof ThreatIntelligenceRoute
  '/training': typeof TrainingRoute
  '/verify-member': typeof VerifyMemberRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/awards': typeof AdminAwardsRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/check-in': typeof AdminCheckInRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/communities': typeof AdminCommunitiesRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/cpd': typeof AdminCpdRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/learning': typeof AdminLearningRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/mentorship': typeof AdminMentorshipRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/speakers': typeof AdminSpeakersRoute
  '/admin/users': typeof AdminUsersRoute
  '/awards/nominate': typeof AwardsNominateRoute
  '/careers/$id': typeof CareersIdRoute
  '/conference/invite': typeof ConferenceInviteRoute
  '/conference/lookup': typeof ConferenceLookupRoute
  '/conference/register': typeof ConferenceRegisterRoute
  '/conference/speak': typeof ConferenceSpeakRoute
  '/conference/sponsor': typeof ConferenceSponsorRoute
  '/conferences/$slug': typeof ConferencesSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/members/directory': typeof MembersDirectoryRoute
  '/membership/apply': typeof MembershipApplyRoute
  '/news/$slug': typeof NewsSlugRoute
  '/payments/callback': typeof PaymentsCallbackRoute
  '/portal/application': typeof PortalApplicationRoute
  '/portal/apply': typeof PortalApplyRoute
  '/portal/card': typeof PortalCardRoute
  '/portal/careers': typeof PortalCareersRoute
  '/portal/certificates': typeof PortalCertificatesRoute
  '/portal/chat': typeof PortalChatRoute
  '/portal/communities': typeof PortalCommunitiesRoute
  '/portal/corporate': typeof PortalCorporateRoute
  '/portal/cpd': typeof PortalCpdRoute
  '/portal/events': typeof PortalEventsRoute
  '/portal/learning': typeof PortalLearningRoute
  '/portal/library': typeof PortalLibraryRouteWithChildren
  '/portal/mentorship': typeof PortalMentorshipRoute
  '/portal/messages': typeof PortalMessagesRouteWithChildren
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/payments': typeof PortalPaymentsRoute
  '/portal/privacy': typeof PortalPrivacyRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/renew': typeof PortalRenewRoute
  '/portal/support': typeof PortalSupportRoute
  '/portal/threats': typeof PortalThreatsRoute
  '/portal/training': typeof PortalTrainingRouteWithChildren
  '/register/verify': typeof RegisterVerifyRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/admin/members/$id': typeof AdminMembersIdRoute
  '/conferences/$slug/register': typeof ConferencesSlugRegisterRoute
  '/portal/conference/register': typeof PortalConferenceRegisterRoute
  '/portal/employer/jobs': typeof PortalEmployerJobsRoute
  '/portal/library/$id': typeof PortalLibraryIdRoute
  '/portal/messages/$threadId': typeof PortalMessagesThreadIdRoute
  '/portal/training/$slug': typeof PortalTrainingSlugRoute
  '/seminars/$slug/register': typeof SeminarsSlugRegisterRoute
  '/portal/training/': typeof PortalTrainingIndexRoute
  '/portal/library/resource/$id': typeof PortalLibraryResourceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-login': typeof AdminLoginRoute
  '/awards': typeof AwardsRoute
  '/benefits': typeof BenefitsRoute
  '/careers': typeof CareersRoute
  '/communities': typeof CommunitiesRoute
  '/conference': typeof ConferenceRoute
  '/conferences': typeof ConferencesRoute
  '/contact': typeof ContactRoute
  '/cookie-settings': typeof CookieSettingsRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/mentorship': typeof MentorshipRoute
  '/news': typeof NewsRoute
  '/partnerships': typeof PartnershipsRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/support': typeof SupportRoute
  '/threat-intelligence': typeof ThreatIntelligenceRoute
  '/training': typeof TrainingRoute
  '/verify-member': typeof VerifyMemberRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/awards': typeof AdminAwardsRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/check-in': typeof AdminCheckInRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/communities': typeof AdminCommunitiesRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/cpd': typeof AdminCpdRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/learning': typeof AdminLearningRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/mentorship': typeof AdminMentorshipRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/speakers': typeof AdminSpeakersRoute
  '/admin/users': typeof AdminUsersRoute
  '/awards/nominate': typeof AwardsNominateRoute
  '/careers/$id': typeof CareersIdRoute
  '/conference/invite': typeof ConferenceInviteRoute
  '/conference/lookup': typeof ConferenceLookupRoute
  '/conference/register': typeof ConferenceRegisterRoute
  '/conference/speak': typeof ConferenceSpeakRoute
  '/conference/sponsor': typeof ConferenceSponsorRoute
  '/conferences/$slug': typeof ConferencesSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/members/directory': typeof MembersDirectoryRoute
  '/membership/apply': typeof MembershipApplyRoute
  '/news/$slug': typeof NewsSlugRoute
  '/payments/callback': typeof PaymentsCallbackRoute
  '/portal/application': typeof PortalApplicationRoute
  '/portal/apply': typeof PortalApplyRoute
  '/portal/card': typeof PortalCardRoute
  '/portal/careers': typeof PortalCareersRoute
  '/portal/certificates': typeof PortalCertificatesRoute
  '/portal/chat': typeof PortalChatRoute
  '/portal/communities': typeof PortalCommunitiesRoute
  '/portal/corporate': typeof PortalCorporateRoute
  '/portal/cpd': typeof PortalCpdRoute
  '/portal/events': typeof PortalEventsRoute
  '/portal/learning': typeof PortalLearningRoute
  '/portal/library': typeof PortalLibraryRouteWithChildren
  '/portal/mentorship': typeof PortalMentorshipRoute
  '/portal/messages': typeof PortalMessagesRouteWithChildren
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/payments': typeof PortalPaymentsRoute
  '/portal/privacy': typeof PortalPrivacyRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/renew': typeof PortalRenewRoute
  '/portal/support': typeof PortalSupportRoute
  '/portal/threats': typeof PortalThreatsRoute
  '/register/verify': typeof RegisterVerifyRoute
  '/admin': typeof AdminIndexRoute
  '/portal': typeof PortalIndexRoute
  '/admin/applications/$id': typeof AdminApplicationsIdRoute
  '/admin/members/$id': typeof AdminMembersIdRoute
  '/conferences/$slug/register': typeof ConferencesSlugRegisterRoute
  '/portal/conference/register': typeof PortalConferenceRegisterRoute
  '/portal/employer/jobs': typeof PortalEmployerJobsRoute
  '/portal/library/$id': typeof PortalLibraryIdRoute
  '/portal/messages/$threadId': typeof PortalMessagesThreadIdRoute
  '/portal/training/$slug': typeof PortalTrainingSlugRoute
  '/seminars/$slug/register': typeof SeminarsSlugRegisterRoute
  '/portal/training': typeof PortalTrainingIndexRoute
  '/portal/library/resource/$id': typeof PortalLibraryResourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/awards': typeof AwardsRoute
  '/benefits': typeof BenefitsRoute
  '/careers': typeof CareersRoute
  '/communities': typeof CommunitiesRoute
  '/conference': typeof ConferenceRoute
  '/conferences': typeof ConferencesRoute
  '/contact': typeof ContactRoute
  '/cookie-settings': typeof CookieSettingsRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/mentorship': typeof MentorshipRoute
  '/news': typeof NewsRoute
  '/partnerships': typeof PartnershipsRoute
  '/portal': typeof PortalRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/support': typeof SupportRoute
  '/threat-intelligence': typeof ThreatIntelligenceRoute
  '/training': typeof TrainingRoute
  '/verify-member': typeof VerifyMemberRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/awards': typeof AdminAwardsRoute
  '/admin/chat': typeof AdminChatRoute
  '/admin/check-in': typeof AdminCheckInRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/communities': typeof AdminCommunitiesRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/cpd': typeof AdminCpdRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/fees': typeof AdminFeesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/learning': typeof AdminLearningRoute
  '/admin/legal': typeof AdminLegalRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/mentorship': typeof AdminMentorshipRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/speakers': typeof AdminSpeakersRoute
  '/admin/users': typeof AdminUsersRoute
  '/awards_/nominate': typeof AwardsNominateRoute
  '/careers_/$id': typeof CareersIdRoute
  '/conference_/invite': typeof ConferenceInviteRoute
  '/conference_/lookup': typeof ConferenceLookupRoute
  '/conference_/register': typeof ConferenceRegisterRoute
  '/conference_/speak': typeof ConferenceSpeakRoute
  '/conference_/sponsor': typeof ConferenceSponsorRoute
  '/conferences_/$slug': typeof ConferencesSlugRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/members/directory': typeof MembersDirectoryRoute
  '/membership_/apply': typeof MembershipApplyRoute
  '/news_/$slug': typeof NewsSlugRoute
  '/payments/callback': typeof PaymentsCallbackRoute
  '/portal/application': typeof PortalApplicationRoute
  '/portal/apply': typeof PortalApplyRoute
  '/portal/card': typeof PortalCardRoute
  '/portal/careers': typeof PortalCareersRoute
  '/portal/certificates': typeof PortalCertificatesRoute
  '/portal/chat': typeof PortalChatRoute
  '/portal/communities': typeof PortalCommunitiesRoute
  '/portal/corporate': typeof PortalCorporateRoute
  '/portal/cpd': typeof PortalCpdRoute
  '/portal/events': typeof PortalEventsRoute
  '/portal/learning': typeof PortalLearningRoute
  '/portal/library': typeof PortalLibraryRouteWithChildren
  '/portal/mentorship': typeof PortalMentorshipRoute
  '/portal/messages': typeof PortalMessagesRouteWithChildren
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/payments': typeof PortalPaymentsRoute
  '/portal/privacy': typeof PortalPrivacyRoute
  '/portal/profile': typeof PortalProfileRoute
  '/portal/renew': typeof PortalRenewRoute
  '/portal/support': typeof PortalSupportRoute
  '/portal/threats': typeof PortalThreatsRoute
  '/portal/training': typeof PortalTrainingRouteWithChildren
  '/register_/verify': typeof RegisterVerifyRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/admin/applications_/$id': typeof AdminApplicationsIdRoute
  '/admin/members_/$id': typeof AdminMembersIdRoute
  '/conferences_/$slug_/register': typeof ConferencesSlugRegisterRoute
  '/portal/conference/register': typeof PortalConferenceRegisterRoute
  '/portal/employer/jobs': typeof PortalEmployerJobsRoute
  '/portal/library/$id': typeof PortalLibraryIdRoute
  '/portal/messages/$threadId': typeof PortalMessagesThreadIdRoute
  '/portal/training/$slug': typeof PortalTrainingSlugRoute
  '/seminars/$slug/register': typeof SeminarsSlugRegisterRoute
  '/portal/training/': typeof PortalTrainingIndexRoute
  '/portal/library/resource/$id': typeof PortalLibraryResourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/awards'
    | '/benefits'
    | '/careers'
    | '/communities'
    | '/conference'
    | '/conferences'
    | '/contact'
    | '/cookie-settings'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/membership'
    | '/mentorship'
    | '/news'
    | '/partnerships'
    | '/portal'
    | '/register'
    | '/reset-password'
    | '/resources'
    | '/support'
    | '/threat-intelligence'
    | '/training'
    | '/verify-member'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/awards'
    | '/admin/chat'
    | '/admin/check-in'
    | '/admin/cms'
    | '/admin/communities'
    | '/admin/contacts'
    | '/admin/cpd'
    | '/admin/events'
    | '/admin/faq'
    | '/admin/fees'
    | '/admin/jobs'
    | '/admin/learning'
    | '/admin/legal'
    | '/admin/members'
    | '/admin/mentorship'
    | '/admin/payments'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/speakers'
    | '/admin/users'
    | '/awards/nominate'
    | '/careers/$id'
    | '/conference/invite'
    | '/conference/lookup'
    | '/conference/register'
    | '/conference/speak'
    | '/conference/sponsor'
    | '/conferences/$slug'
    | '/legal/$slug'
    | '/members/directory'
    | '/membership/apply'
    | '/news/$slug'
    | '/payments/callback'
    | '/portal/application'
    | '/portal/apply'
    | '/portal/card'
    | '/portal/careers'
    | '/portal/certificates'
    | '/portal/chat'
    | '/portal/communities'
    | '/portal/corporate'
    | '/portal/cpd'
    | '/portal/events'
    | '/portal/learning'
    | '/portal/library'
    | '/portal/mentorship'
    | '/portal/messages'
    | '/portal/notifications'
    | '/portal/payments'
    | '/portal/privacy'
    | '/portal/profile'
    | '/portal/renew'
    | '/portal/support'
    | '/portal/threats'
    | '/portal/training'
    | '/register/verify'
    | '/admin/'
    | '/portal/'
    | '/admin/applications/$id'
    | '/admin/members/$id'
    | '/conferences/$slug/register'
    | '/portal/conference/register'
    | '/portal/employer/jobs'
    | '/portal/library/$id'
    | '/portal/messages/$threadId'
    | '/portal/training/$slug'
    | '/seminars/$slug/register'
    | '/portal/training/'
    | '/portal/library/resource/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin-login'
    | '/awards'
    | '/benefits'
    | '/careers'
    | '/communities'
    | '/conference'
    | '/conferences'
    | '/contact'
    | '/cookie-settings'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/membership'
    | '/mentorship'
    | '/news'
    | '/partnerships'
    | '/register'
    | '/reset-password'
    | '/resources'
    | '/support'
    | '/threat-intelligence'
    | '/training'
    | '/verify-member'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/awards'
    | '/admin/chat'
    | '/admin/check-in'
    | '/admin/cms'
    | '/admin/communities'
    | '/admin/contacts'
    | '/admin/cpd'
    | '/admin/events'
    | '/admin/faq'
    | '/admin/fees'
    | '/admin/jobs'
    | '/admin/learning'
    | '/admin/legal'
    | '/admin/members'
    | '/admin/mentorship'
    | '/admin/payments'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/speakers'
    | '/admin/users'
    | '/awards/nominate'
    | '/careers/$id'
    | '/conference/invite'
    | '/conference/lookup'
    | '/conference/register'
    | '/conference/speak'
    | '/conference/sponsor'
    | '/conferences/$slug'
    | '/legal/$slug'
    | '/members/directory'
    | '/membership/apply'
    | '/news/$slug'
    | '/payments/callback'
    | '/portal/application'
    | '/portal/apply'
    | '/portal/card'
    | '/portal/careers'
    | '/portal/certificates'
    | '/portal/chat'
    | '/portal/communities'
    | '/portal/corporate'
    | '/portal/cpd'
    | '/portal/events'
    | '/portal/learning'
    | '/portal/library'
    | '/portal/mentorship'
    | '/portal/messages'
    | '/portal/notifications'
    | '/portal/payments'
    | '/portal/privacy'
    | '/portal/profile'
    | '/portal/renew'
    | '/portal/support'
    | '/portal/threats'
    | '/register/verify'
    | '/admin'
    | '/portal'
    | '/admin/applications/$id'
    | '/admin/members/$id'
    | '/conferences/$slug/register'
    | '/portal/conference/register'
    | '/portal/employer/jobs'
    | '/portal/library/$id'
    | '/portal/messages/$threadId'
    | '/portal/training/$slug'
    | '/seminars/$slug/register'
    | '/portal/training'
    | '/portal/library/resource/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admin-login'
    | '/awards'
    | '/benefits'
    | '/careers'
    | '/communities'
    | '/conference'
    | '/conferences'
    | '/contact'
    | '/cookie-settings'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/membership'
    | '/mentorship'
    | '/news'
    | '/partnerships'
    | '/portal'
    | '/register'
    | '/reset-password'
    | '/resources'
    | '/support'
    | '/threat-intelligence'
    | '/training'
    | '/verify-member'
    | '/admin/applications'
    | '/admin/audit'
    | '/admin/awards'
    | '/admin/chat'
    | '/admin/check-in'
    | '/admin/cms'
    | '/admin/communities'
    | '/admin/contacts'
    | '/admin/cpd'
    | '/admin/events'
    | '/admin/faq'
    | '/admin/fees'
    | '/admin/jobs'
    | '/admin/learning'
    | '/admin/legal'
    | '/admin/members'
    | '/admin/mentorship'
    | '/admin/payments'
    | '/admin/profile'
    | '/admin/reports'
    | '/admin/speakers'
    | '/admin/users'
    | '/awards_/nominate'
    | '/careers_/$id'
    | '/conference_/invite'
    | '/conference_/lookup'
    | '/conference_/register'
    | '/conference_/speak'
    | '/conference_/sponsor'
    | '/conferences_/$slug'
    | '/legal/$slug'
    | '/members/directory'
    | '/membership_/apply'
    | '/news_/$slug'
    | '/payments/callback'
    | '/portal/application'
    | '/portal/apply'
    | '/portal/card'
    | '/portal/careers'
    | '/portal/certificates'
    | '/portal/chat'
    | '/portal/communities'
    | '/portal/corporate'
    | '/portal/cpd'
    | '/portal/events'
    | '/portal/learning'
    | '/portal/library'
    | '/portal/mentorship'
    | '/portal/messages'
    | '/portal/notifications'
    | '/portal/payments'
    | '/portal/privacy'
    | '/portal/profile'
    | '/portal/renew'
    | '/portal/support'
    | '/portal/threats'
    | '/portal/training'
    | '/register_/verify'
    | '/admin/'
    | '/portal/'
    | '/admin/applications_/$id'
    | '/admin/members_/$id'
    | '/conferences_/$slug_/register'
    | '/portal/conference/register'
    | '/portal/employer/jobs'
    | '/portal/library/$id'
    | '/portal/messages/$threadId'
    | '/portal/training/$slug'
    | '/seminars/$slug/register'
    | '/portal/training/'
    | '/portal/library/resource/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AwardsRoute: typeof AwardsRoute
  BenefitsRoute: typeof BenefitsRoute
  CareersRoute: typeof CareersRoute
  CommunitiesRoute: typeof CommunitiesRoute
  ConferenceRoute: typeof ConferenceRoute
  ConferencesRoute: typeof ConferencesRoute
  ContactRoute: typeof ContactRoute
  CookieSettingsRoute: typeof CookieSettingsRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MembershipRoute: typeof MembershipRoute
  MentorshipRoute: typeof MentorshipRoute
  NewsRoute: typeof NewsRoute
  PartnershipsRoute: typeof PartnershipsRoute
  PortalRoute: typeof PortalRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  SupportRoute: typeof SupportRoute
  ThreatIntelligenceRoute: typeof ThreatIntelligenceRoute
  TrainingRoute: typeof TrainingRoute
  VerifyMemberRoute: typeof VerifyMemberRoute
  AwardsNominateRoute: typeof AwardsNominateRoute
  CareersIdRoute: typeof CareersIdRoute
  ConferenceInviteRoute: typeof ConferenceInviteRoute
  ConferenceLookupRoute: typeof ConferenceLookupRoute
  ConferenceRegisterRoute: typeof ConferenceRegisterRoute
  ConferenceSpeakRoute: typeof ConferenceSpeakRoute
  ConferenceSponsorRoute: typeof ConferenceSponsorRoute
  ConferencesSlugRoute: typeof ConferencesSlugRoute
  LegalSlugRoute: typeof LegalSlugRoute
  MembersDirectoryRoute: typeof MembersDirectoryRoute
  MembershipApplyRoute: typeof MembershipApplyRoute
  NewsSlugRoute: typeof NewsSlugRoute
  PaymentsCallbackRoute: typeof PaymentsCallbackRoute
  RegisterVerifyRoute: typeof RegisterVerifyRoute
  ConferencesSlugRegisterRoute: typeof ConferencesSlugRegisterRoute
  SeminarsSlugRegisterRoute: typeof SeminarsSlugRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards': {
      id: '/awards'
      path: '/awards'
      fullPath: '/awards'
      preLoaderRoute: typeof AwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benefits': {
      id: '/benefits'
      path: '/benefits'
      fullPath: '/benefits'
      preLoaderRoute: typeof BenefitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities': {
      id: '/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof CommunitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conference': {
      id: '/conference'
      path: '/conference'
      fullPath: '/conference'
      preLoaderRoute: typeof ConferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conferences': {
      id: '/conferences'
      path: '/conferences'
      fullPath: '/conferences'
      preLoaderRoute: typeof ConferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-settings': {
      id: '/cookie-settings'
      path: '/cookie-settings'
      fullPath: '/cookie-settings'
      preLoaderRoute: typeof CookieSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentorship': {
      id: '/mentorship'
      path: '/mentorship'
      fullPath: '/mentorship'
      preLoaderRoute: typeof MentorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnerships': {
      id: '/partnerships'
      path: '/partnerships'
      fullPath: '/partnerships'
      preLoaderRoute: typeof PartnershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat-intelligence': {
      id: '/threat-intelligence'
      path: '/threat-intelligence'
      fullPath: '/threat-intelligence'
      preLoaderRoute: typeof ThreatIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-member': {
      id: '/verify-member'
      path: '/verify-member'
      fullPath: '/verify-member'
      preLoaderRoute: typeof VerifyMemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/awards': {
      id: '/admin/awards'
      path: '/awards'
      fullPath: '/admin/awards'
      preLoaderRoute: typeof AdminAwardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chat': {
      id: '/admin/chat'
      path: '/chat'
      fullPath: '/admin/chat'
      preLoaderRoute: typeof AdminChatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/check-in': {
      id: '/admin/check-in'
      path: '/check-in'
      fullPath: '/admin/check-in'
      preLoaderRoute: typeof AdminCheckInRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/communities': {
      id: '/admin/communities'
      path: '/communities'
      fullPath: '/admin/communities'
      preLoaderRoute: typeof AdminCommunitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cpd': {
      id: '/admin/cpd'
      path: '/cpd'
      fullPath: '/admin/cpd'
      preLoaderRoute: typeof AdminCpdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faq': {
      id: '/admin/faq'
      path: '/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AdminFaqRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fees': {
      id: '/admin/fees'
      path: '/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AdminFeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/learning': {
      id: '/admin/learning'
      path: '/learning'
      fullPath: '/admin/learning'
      preLoaderRoute: typeof AdminLearningRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/legal': {
      id: '/admin/legal'
      path: '/legal'
      fullPath: '/admin/legal'
      preLoaderRoute: typeof AdminLegalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mentorship': {
      id: '/admin/mentorship'
      path: '/mentorship'
      fullPath: '/admin/mentorship'
      preLoaderRoute: typeof AdminMentorshipRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/speakers': {
      id: '/admin/speakers'
      path: '/speakers'
      fullPath: '/admin/speakers'
      preLoaderRoute: typeof AdminSpeakersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/awards_/nominate': {
      id: '/awards_/nominate'
      path: '/awards/nominate'
      fullPath: '/awards/nominate'
      preLoaderRoute: typeof AwardsNominateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers_/$id': {
      id: '/careers_/$id'
      path: '/careers/$id'
      fullPath: '/careers/$id'
      preLoaderRoute: typeof CareersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conference_/invite': {
      id: '/conference_/invite'
      path: '/conference/invite'
      fullPath: '/conference/invite'
      preLoaderRoute: typeof ConferenceInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conference_/lookup': {
      id: '/conference_/lookup'
      path: '/conference/lookup'
      fullPath: '/conference/lookup'
      preLoaderRoute: typeof ConferenceLookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conference_/register': {
      id: '/conference_/register'
      path: '/conference/register'
      fullPath: '/conference/register'
      preLoaderRoute: typeof ConferenceRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conference_/speak': {
      id: '/conference_/speak'
      path: '/conference/speak'
      fullPath: '/conference/speak'
      preLoaderRoute: typeof ConferenceSpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conference_/sponsor': {
      id: '/conference_/sponsor'
      path: '/conference/sponsor'
      fullPath: '/conference/sponsor'
      preLoaderRoute: typeof ConferenceSponsorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conferences_/$slug': {
      id: '/conferences_/$slug'
      path: '/conferences/$slug'
      fullPath: '/conferences/$slug'
      preLoaderRoute: typeof ConferencesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/directory': {
      id: '/members/directory'
      path: '/members/directory'
      fullPath: '/members/directory'
      preLoaderRoute: typeof MembersDirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership_/apply': {
      id: '/membership_/apply'
      path: '/membership/apply'
      fullPath: '/membership/apply'
      preLoaderRoute: typeof MembershipApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news_/$slug': {
      id: '/news_/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/callback': {
      id: '/payments/callback'
      path: '/payments/callback'
      fullPath: '/payments/callback'
      preLoaderRoute: typeof PaymentsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/application': {
      id: '/portal/application'
      path: '/application'
      fullPath: '/portal/application'
      preLoaderRoute: typeof PortalApplicationRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/apply': {
      id: '/portal/apply'
      path: '/apply'
      fullPath: '/portal/apply'
      preLoaderRoute: typeof PortalApplyRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/card': {
      id: '/portal/card'
      path: '/card'
      fullPath: '/portal/card'
      preLoaderRoute: typeof PortalCardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/careers': {
      id: '/portal/careers'
      path: '/careers'
      fullPath: '/portal/careers'
      preLoaderRoute: typeof PortalCareersRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/certificates': {
      id: '/portal/certificates'
      path: '/certificates'
      fullPath: '/portal/certificates'
      preLoaderRoute: typeof PortalCertificatesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/chat': {
      id: '/portal/chat'
      path: '/chat'
      fullPath: '/portal/chat'
      preLoaderRoute: typeof PortalChatRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/communities': {
      id: '/portal/communities'
      path: '/communities'
      fullPath: '/portal/communities'
      preLoaderRoute: typeof PortalCommunitiesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/corporate': {
      id: '/portal/corporate'
      path: '/corporate'
      fullPath: '/portal/corporate'
      preLoaderRoute: typeof PortalCorporateRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/cpd': {
      id: '/portal/cpd'
      path: '/cpd'
      fullPath: '/portal/cpd'
      preLoaderRoute: typeof PortalCpdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/events': {
      id: '/portal/events'
      path: '/events'
      fullPath: '/portal/events'
      preLoaderRoute: typeof PortalEventsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/learning': {
      id: '/portal/learning'
      path: '/learning'
      fullPath: '/portal/learning'
      preLoaderRoute: typeof PortalLearningRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/library': {
      id: '/portal/library'
      path: '/library'
      fullPath: '/portal/library'
      preLoaderRoute: typeof PortalLibraryRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/mentorship': {
      id: '/portal/mentorship'
      path: '/mentorship'
      fullPath: '/portal/mentorship'
      preLoaderRoute: typeof PortalMentorshipRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/messages': {
      id: '/portal/messages'
      path: '/messages'
      fullPath: '/portal/messages'
      preLoaderRoute: typeof PortalMessagesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/notifications': {
      id: '/portal/notifications'
      path: '/notifications'
      fullPath: '/portal/notifications'
      preLoaderRoute: typeof PortalNotificationsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/payments': {
      id: '/portal/payments'
      path: '/payments'
      fullPath: '/portal/payments'
      preLoaderRoute: typeof PortalPaymentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/privacy': {
      id: '/portal/privacy'
      path: '/privacy'
      fullPath: '/portal/privacy'
      preLoaderRoute: typeof PortalPrivacyRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/renew': {
      id: '/portal/renew'
      path: '/renew'
      fullPath: '/portal/renew'
      preLoaderRoute: typeof PortalRenewRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/support': {
      id: '/portal/support'
      path: '/support'
      fullPath: '/portal/support'
      preLoaderRoute: typeof PortalSupportRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/threats': {
      id: '/portal/threats'
      path: '/threats'
      fullPath: '/portal/threats'
      preLoaderRoute: typeof PortalThreatsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/training': {
      id: '/portal/training'
      path: '/training'
      fullPath: '/portal/training'
      preLoaderRoute: typeof PortalTrainingRouteImport
      parentRoute: typeof PortalRoute
    }
    '/register_/verify': {
      id: '/register_/verify'
      path: '/register/verify'
      fullPath: '/register/verify'
      preLoaderRoute: typeof RegisterVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/applications_/$id': {
      id: '/admin/applications_/$id'
      path: '/applications/$id'
      fullPath: '/admin/applications/$id'
      preLoaderRoute: typeof AdminApplicationsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members_/$id': {
      id: '/admin/members_/$id'
      path: '/members/$id'
      fullPath: '/admin/members/$id'
      preLoaderRoute: typeof AdminMembersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/conferences_/$slug_/register': {
      id: '/conferences_/$slug_/register'
      path: '/conferences/$slug/register'
      fullPath: '/conferences/$slug/register'
      preLoaderRoute: typeof ConferencesSlugRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/conference/register': {
      id: '/portal/conference/register'
      path: '/conference/register'
      fullPath: '/portal/conference/register'
      preLoaderRoute: typeof PortalConferenceRegisterRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/employer/jobs': {
      id: '/portal/employer/jobs'
      path: '/employer/jobs'
      fullPath: '/portal/employer/jobs'
      preLoaderRoute: typeof PortalEmployerJobsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/library/$id': {
      id: '/portal/library/$id'
      path: '/$id'
      fullPath: '/portal/library/$id'
      preLoaderRoute: typeof PortalLibraryIdRouteImport
      parentRoute: typeof PortalLibraryRoute
    }
    '/portal/messages/$threadId': {
      id: '/portal/messages/$threadId'
      path: '/$threadId'
      fullPath: '/portal/messages/$threadId'
      preLoaderRoute: typeof PortalMessagesThreadIdRouteImport
      parentRoute: typeof PortalMessagesRoute
    }
    '/portal/training/': {
      id: '/portal/training/'
      path: '/'
      fullPath: '/portal/training/'
      preLoaderRoute: typeof PortalTrainingIndexRouteImport
      parentRoute: typeof PortalTrainingRoute
    }
    '/portal/training/$slug': {
      id: '/portal/training/$slug'
      path: '/$slug'
      fullPath: '/portal/training/$slug'
      preLoaderRoute: typeof PortalTrainingSlugRouteImport
      parentRoute: typeof PortalTrainingRoute
    }
    '/seminars/$slug/register': {
      id: '/seminars/$slug/register'
      path: '/seminars/$slug/register'
      fullPath: '/seminars/$slug/register'
      preLoaderRoute: typeof SeminarsSlugRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/library/resource/$id': {
      id: '/portal/library/resource/$id'
      path: '/resource/$id'
      fullPath: '/portal/library/resource/$id'
      preLoaderRoute: typeof PortalLibraryResourceIdRouteImport
      parentRoute: typeof PortalLibraryRoute
    }
  }
}

interface AdminRouteChildren {
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminAwardsRoute: typeof AdminAwardsRoute
  AdminChatRoute: typeof AdminChatRoute
  AdminCheckInRoute: typeof AdminCheckInRoute
  AdminCmsRoute: typeof AdminCmsRoute
  AdminCommunitiesRoute: typeof AdminCommunitiesRoute
  AdminContactsRoute: typeof AdminContactsRoute
  AdminCpdRoute: typeof AdminCpdRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminFaqRoute: typeof AdminFaqRoute
  AdminFeesRoute: typeof AdminFeesRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminLearningRoute: typeof AdminLearningRoute
  AdminLegalRoute: typeof AdminLegalRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminMentorshipRoute: typeof AdminMentorshipRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSpeakersRoute: typeof AdminSpeakersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminApplicationsIdRoute: typeof AdminApplicationsIdRoute
  AdminMembersIdRoute: typeof AdminMembersIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminAwardsRoute: AdminAwardsRoute,
  AdminChatRoute: AdminChatRoute,
  AdminCheckInRoute: AdminCheckInRoute,
  AdminCmsRoute: AdminCmsRoute,
  AdminCommunitiesRoute: AdminCommunitiesRoute,
  AdminContactsRoute: AdminContactsRoute,
  AdminCpdRoute: AdminCpdRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminFaqRoute: AdminFaqRoute,
  AdminFeesRoute: AdminFeesRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminLearningRoute: AdminLearningRoute,
  AdminLegalRoute: AdminLegalRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminMentorshipRoute: AdminMentorshipRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSpeakersRoute: AdminSpeakersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminApplicationsIdRoute: AdminApplicationsIdRoute,
  AdminMembersIdRoute: AdminMembersIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PortalLibraryRouteChildren {
  PortalLibraryIdRoute: typeof PortalLibraryIdRoute
  PortalLibraryResourceIdRoute: typeof PortalLibraryResourceIdRoute
}

const PortalLibraryRouteChildren: PortalLibraryRouteChildren = {
  PortalLibraryIdRoute: PortalLibraryIdRoute,
  PortalLibraryResourceIdRoute: PortalLibraryResourceIdRoute,
}

const PortalLibraryRouteWithChildren = PortalLibraryRoute._addFileChildren(
  PortalLibraryRouteChildren,
)

interface PortalMessagesRouteChildren {
  PortalMessagesThreadIdRoute: typeof PortalMessagesThreadIdRoute
}

const PortalMessagesRouteChildren: PortalMessagesRouteChildren = {
  PortalMessagesThreadIdRoute: PortalMessagesThreadIdRoute,
}

const PortalMessagesRouteWithChildren = PortalMessagesRoute._addFileChildren(
  PortalMessagesRouteChildren,
)

interface PortalTrainingRouteChildren {
  PortalTrainingSlugRoute: typeof PortalTrainingSlugRoute
  PortalTrainingIndexRoute: typeof PortalTrainingIndexRoute
}

const PortalTrainingRouteChildren: PortalTrainingRouteChildren = {
  PortalTrainingSlugRoute: PortalTrainingSlugRoute,
  PortalTrainingIndexRoute: PortalTrainingIndexRoute,
}

const PortalTrainingRouteWithChildren = PortalTrainingRoute._addFileChildren(
  PortalTrainingRouteChildren,
)

interface PortalRouteChildren {
  PortalApplicationRoute: typeof PortalApplicationRoute
  PortalApplyRoute: typeof PortalApplyRoute
  PortalCardRoute: typeof PortalCardRoute
  PortalCareersRoute: typeof PortalCareersRoute
  PortalCertificatesRoute: typeof PortalCertificatesRoute
  PortalChatRoute: typeof PortalChatRoute
  PortalCommunitiesRoute: typeof PortalCommunitiesRoute
  PortalCorporateRoute: typeof PortalCorporateRoute
  PortalCpdRoute: typeof PortalCpdRoute
  PortalEventsRoute: typeof PortalEventsRoute
  PortalLearningRoute: typeof PortalLearningRoute
  PortalLibraryRoute: typeof PortalLibraryRouteWithChildren
  PortalMentorshipRoute: typeof PortalMentorshipRoute
  PortalMessagesRoute: typeof PortalMessagesRouteWithChildren
  PortalNotificationsRoute: typeof PortalNotificationsRoute
  PortalPaymentsRoute: typeof PortalPaymentsRoute
  PortalPrivacyRoute: typeof PortalPrivacyRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalRenewRoute: typeof PortalRenewRoute
  PortalSupportRoute: typeof PortalSupportRoute
  PortalThreatsRoute: typeof PortalThreatsRoute
  PortalTrainingRoute: typeof PortalTrainingRouteWithChildren
  PortalIndexRoute: typeof PortalIndexRoute
  PortalConferenceRegisterRoute: typeof PortalConferenceRegisterRoute
  PortalEmployerJobsRoute: typeof PortalEmployerJobsRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalApplicationRoute: PortalApplicationRoute,
  PortalApplyRoute: PortalApplyRoute,
  PortalCardRoute: PortalCardRoute,
  PortalCareersRoute: PortalCareersRoute,
  PortalCertificatesRoute: PortalCertificatesRoute,
  PortalChatRoute: PortalChatRoute,
  PortalCommunitiesRoute: PortalCommunitiesRoute,
  PortalCorporateRoute: PortalCorporateRoute,
  PortalCpdRoute: PortalCpdRoute,
  PortalEventsRoute: PortalEventsRoute,
  PortalLearningRoute: PortalLearningRoute,
  PortalLibraryRoute: PortalLibraryRouteWithChildren,
  PortalMentorshipRoute: PortalMentorshipRoute,
  PortalMessagesRoute: PortalMessagesRouteWithChildren,
  PortalNotificationsRoute: PortalNotificationsRoute,
  PortalPaymentsRoute: PortalPaymentsRoute,
  PortalPrivacyRoute: PortalPrivacyRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalRenewRoute: PortalRenewRoute,
  PortalSupportRoute: PortalSupportRoute,
  PortalThreatsRoute: PortalThreatsRoute,
  PortalTrainingRoute: PortalTrainingRouteWithChildren,
  PortalIndexRoute: PortalIndexRoute,
  PortalConferenceRegisterRoute: PortalConferenceRegisterRoute,
  PortalEmployerJobsRoute: PortalEmployerJobsRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AwardsRoute: AwardsRoute,
  BenefitsRoute: BenefitsRoute,
  CareersRoute: CareersRoute,
  CommunitiesRoute: CommunitiesRoute,
  ConferenceRoute: ConferenceRoute,
  ConferencesRoute: ConferencesRoute,
  ContactRoute: ContactRoute,
  CookieSettingsRoute: CookieSettingsRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MembershipRoute: MembershipRoute,
  MentorshipRoute: MentorshipRoute,
  NewsRoute: NewsRoute,
  PartnershipsRoute: PartnershipsRoute,
  PortalRoute: PortalRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  SupportRoute: SupportRoute,
  ThreatIntelligenceRoute: ThreatIntelligenceRoute,
  TrainingRoute: TrainingRoute,
  VerifyMemberRoute: VerifyMemberRoute,
  AwardsNominateRoute: AwardsNominateRoute,
  CareersIdRoute: CareersIdRoute,
  ConferenceInviteRoute: ConferenceInviteRoute,
  ConferenceLookupRoute: ConferenceLookupRoute,
  ConferenceRegisterRoute: ConferenceRegisterRoute,
  ConferenceSpeakRoute: ConferenceSpeakRoute,
  ConferenceSponsorRoute: ConferenceSponsorRoute,
  ConferencesSlugRoute: ConferencesSlugRoute,
  LegalSlugRoute: LegalSlugRoute,
  MembersDirectoryRoute: MembersDirectoryRoute,
  MembershipApplyRoute: MembershipApplyRoute,
  NewsSlugRoute: NewsSlugRoute,
  PaymentsCallbackRoute: PaymentsCallbackRoute,
  RegisterVerifyRoute: RegisterVerifyRoute,
  ConferencesSlugRegisterRoute: ConferencesSlugRegisterRoute,
  SeminarsSlugRegisterRoute: SeminarsSlugRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
